
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int yen_dolar = 12;
  public static final int yen_euro = 13;
  public static final int euro_yen = 10;
  public static final int dolar_yen = 7;
  public static final int num = 16;
  public static final int euro_sol = 8;
  public static final int EOF = 0;
  public static final int dolar_sol = 5;
  public static final int dolar_euro = 6;
  public static final int error = 1;
  public static final int sol_dolar = 2;
  public static final int sol_yen = 4;
  public static final int parc = 15;
  public static final int para = 14;
  public static final int yen_sol = 11;
  public static final int euro_dolar = 9;
  public static final int sol_euro = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "sol_dolar",
  "sol_euro",
  "sol_yen",
  "dolar_sol",
  "dolar_euro",
  "dolar_yen",
  "euro_sol",
  "euro_dolar",
  "euro_yen",
  "yen_sol",
  "yen_dolar",
  "yen_euro",
  "para",
  "parc",
  "num"
  };
}

