/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.IOException;
import java.io.StringReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import Analizadores.Analizador_Lexico;
import Analizadores.ConnexionBD;
import Analizadores.analisis_sintactico;
import java.io.BufferedReader;
import java.io.StringReader;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import jdk.nashorn.internal.parser.Token;

/**
 *
 * @author james
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        txtImporte1.setBackground(new java.awt.Color(0, 0, 0, 1));
    }

    class jPanelGradient extends JPanel {

        protected void paintComponent(Graphics g) {
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();
            Color color1 = new Color(0, 0, 153);
            Color color2 = new Color(0, 0, 51);
            GradientPaint gp = new GradientPaint(0, 0, color1, 180, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jProgressBar1 = new javax.swing.JProgressBar();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtImporte1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jBoxPais1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jBoxPais2 = new javax.swing.JComboBox<>();
        txtResultado = new javax.swing.JTextField();
        jButtonReturn = new javax.swing.JButton();
        jButtonConverir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new jPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Lucida Sans Unicode", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 0));
        jLabel7.setText("CONVERSOR DE MONEDAS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFocusTraversalPolicyProvider(true);
        jSeparator1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 152, 131, 10));

        txtImporte1.setBackground(new java.awt.Color(0, 51, 0));
        txtImporte1.setForeground(new java.awt.Color(255, 255, 255));
        txtImporte1.setToolTipText("");
        txtImporte1.setBorder(null);
        txtImporte1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtImporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImporte1ActionPerformed(evt);
            }
        });
        jPanel2.add(txtImporte1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 130, 131, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Importe");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 96, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("De");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 84, -1, -1));

        jBoxPais1.setBackground(new java.awt.Color(0, 102, 204));
        jBoxPais1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PEN (S/.)", "DOL ($)", "EUR (€)", "YEN (¥)" }));
        jBoxPais1.setBorder(null);
        jBoxPais1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBoxPais1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxPais1ActionPerformed(evt);
            }
        });
        jPanel2.add(jBoxPais1, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 112, 149, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("A");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 168, 46, -1));

        jBoxPais2.setBackground(new java.awt.Color(0, 102, 204));
        jBoxPais2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DOL ($)", "PEN (S/.)", "EUR (€)", "YEN (¥)" }));
        jBoxPais2.setBorder(null);
        jBoxPais2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBoxPais2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxPais2ActionPerformed(evt);
            }
        });
        jPanel2.add(jBoxPais2, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 202, 149, -1));

        txtResultado.setBackground(new java.awt.Color(0, 0, 0));
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtResultado.setEnabled(false);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        jPanel2.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 320, 139, 45));

        jButtonReturn.setBackground(new java.awt.Color(102, 102, 102));
        jButtonReturn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonReturn.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReturn.setText("⮐");
        jButtonReturn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, -1, -1));

        jButtonConverir.setBackground(new java.awt.Color(0, 102, 204));
        jButtonConverir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConverir.setText("CONVERTIR");
        jButtonConverir.setBorder(null);
        jButtonConverir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConverir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConverirActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonConverir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 140, 43));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo_finanzas.jpg"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 390));

        jTabbedPane1.addTab("Conversor", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 51));
        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista de Historial");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 32, -1, -1));

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 67, -1, -1));

        jPanel5.setBorder(new javax.swing.border.MatteBorder(null));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea2PropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 180, -1, -1));

        jPanel6.setBorder(new javax.swing.border.MatteBorder(null));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTextArea3PropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 430, 90));

        jButton1.setText("Ver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTabbedPane1.addTab("Historial", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBoxPais1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxPais1ActionPerformed
        // TODO add your handling code here:
        // Puedes obtener el valor seleccionado en el combo box

    }//GEN-LAST:event_jBoxPais1ActionPerformed

    private void txtImporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImporte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImporte1ActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void jButtonConverirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConverirActionPerformed
        // TODO add your handling code here:
        String datos = txtImporte1.getText();
        String pais1 = jBoxPais1.getSelectedItem().toString();
        String pais2 = jBoxPais2.getSelectedItem().toString();

        pais1 = pais1.replace(" (S/.)", "");
        pais1 = pais1.replace(" ($)", "");
        pais1 = pais1.replace(" (€)", "");
        pais1 = pais1.replace(" (¥)", "");
        pais2 = pais2.replace(" (S/.)", "");
        pais2 = pais2.replace(" ($)", "");
        pais2 = pais2.replace(" (€)", "");
        pais2 = pais2.replace(" (¥)", "");

        String conversionSymbol = pais1 + "_" + pais2;
        String entradaAnalizador = datos + " " + conversionSymbol;

        Analizador_Lexico lexico = new Analizador_Lexico(new BufferedReader(new StringReader(entradaAnalizador)));
        analisis_sintactico sintactico = new analisis_sintactico(lexico);

        try {
            sintactico.parse();
            txtResultado.setText(sintactico.resultado);
            guardarOperacion(entradaAnalizador, sintactico.resultado);
        } catch (Exception e) {
            e.printStackTrace();
            txtResultado.setText("Error en la conversión.");        
        }

    }//GEN-LAST:event_jButtonConverirActionPerformed

    private void guardarOperacion(String entrada, String resultado) {
        try (Connection connection = ConnexionBD.conectar()) {
            // Crea la declaración SQL para insertar la operación en la tabla del historial
            String sql = "INSERT INTO historial (operacion, resultado, fecha) VALUES (?, ?, NOW())";

            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                statement.setString(1, entrada);
                statement.setString(2, resultado);

                // Ejecuta la consulta
                statement.executeUpdate();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void mostrarHistorial() {
        try (Connection connection = ConnexionBD.conectar()) {
            // Crea la consulta SQL para obtener las últimas 3 operaciones
            String sql = "SELECT operacion, resultado, fecha FROM historial ORDER BY fecha DESC LIMIT 3";

            try (PreparedStatement statement = connection.prepareStatement(sql)) {
                try (ResultSet resultSet = statement.executeQuery()) {
                    // Itera sobre los resultados y actualiza los JTextArea correspondientes
                    int i = 1;
                    while (resultSet.next()) {
                        String operacion = resultSet.getString("operacion");
                        String resultado = resultSet.getString("resultado");
                        String fecha = resultSet.getString("fecha");

                        // Actualiza el correspondiente JTextArea
                        JTextArea textArea = obtenerJTextAreaCorrespondiente(i);
                        textArea.setText("Operación: " + operacion + "\nResultado: " + resultado + "\nFecha: " + fecha);

                        i++;
                    }
                }
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private JTextArea obtenerJTextAreaCorrespondiente(int numero) {
        switch (numero) {
            case 1:
                return jTextArea1;
            case 2:
                return jTextArea2;
            case 3:
                return jTextArea3;
            default:
                throw new IllegalArgumentException("Número de JTextArea no válido: " + numero);
        }
    }


    private void jBoxPais2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxPais2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxPais2ActionPerformed


    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        // TODO add your handling code here:
        // Limpiar los campos de texto y restablecer la selección de los combo box
        txtImporte1.setText("");
        txtResultado.setText("");
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void mostrarHistorialEnJTextArea() {
        // Llama a la función para mostrar el historial
        mostrarHistorial();
    }

    private void jTextArea1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea1PropertyChange
        // TODO add your handling code here:
        mostrarHistorialEnJTextArea();
    }//GEN-LAST:event_jTextArea1PropertyChange

    private void jTextArea2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea2PropertyChange
        // TODO add your handling code here:
        mostrarHistorialEnJTextArea();
    }//GEN-LAST:event_jTextArea2PropertyChange

    private void jTextArea3PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTextArea3PropertyChange
        // TODO add your handling code here:
        mostrarHistorialEnJTextArea();
    }//GEN-LAST:event_jTextArea3PropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        mostrarHistorialEnJTextArea();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jBoxPais1;
    private javax.swing.JComboBox<String> jBoxPais2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonConverir;
    private javax.swing.JButton jButtonReturn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField txtImporte1;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
